spring:
  profiles:
    active: dev


public:
  key:
    value: M1BMbTNoU0tvMTFaVm1NUnplYjJVN3p0QzVIQ1ZYdnpLa1hyMzFBSXdXUQ==

endpoint:
  url:
    value: https://api.unsplash.com/collections

server:
  port: 9000
